# Site settings
title: Renato Personal Website
description: 
# baseurl: "renato.rventre@github.io" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Renato R. Ventre
user_description: I’m graduated in Control and Automation Engineering at Instituto Mauá de Tecnologia and I’ve worked for GM as an intern of Engine and Transmission Laboratory dept for two years. I was responsible for monitoring tests, making reports and checking the continuous improvement projects. Knowledge tools such as Office Package, Matlab, Android Studio, SQL.
user_title: Enginerr of Control and Automation; Software Developer
email: renato.rventre@gmail.com
twitter_username: lorem_ipsum
github_username:  renatorventre
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
